// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPHpR8FiJNrZLkqzeXc28qjAuwk5QQJRg',
    appId: '1:342846124576:web:c2e3e0c8523287cb510245',
    messagingSenderId: '342846124576',
    projectId: 'e-commerce-73113',
    authDomain: 'e-commerce-73113.firebaseapp.com',
    storageBucket: 'e-commerce-73113.firebasestorage.app',
    measurementId: 'G-C3NPFC90SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl_3DcTXKzJ31uJ0jysIJn76qPQNGnrxo',
    appId: '1:342846124576:android:03123473ab673c00510245',
    messagingSenderId: '342846124576',
    projectId: 'e-commerce-73113',
    storageBucket: 'e-commerce-73113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30yEO8mkXe19OcM2J1GF71Z4NQFfTQwc',
    appId: '1:342846124576:ios:d0f10f3edc24d159510245',
    messagingSenderId: '342846124576',
    projectId: 'e-commerce-73113',
    storageBucket: 'e-commerce-73113.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD30yEO8mkXe19OcM2J1GF71Z4NQFfTQwc',
    appId: '1:342846124576:ios:d0f10f3edc24d159510245',
    messagingSenderId: '342846124576',
    projectId: 'e-commerce-73113',
    storageBucket: 'e-commerce-73113.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPHpR8FiJNrZLkqzeXc28qjAuwk5QQJRg',
    appId: '1:342846124576:web:99f74d6ce04abc23510245',
    messagingSenderId: '342846124576',
    projectId: 'e-commerce-73113',
    authDomain: 'e-commerce-73113.firebaseapp.com',
    storageBucket: 'e-commerce-73113.firebasestorage.app',
    measurementId: 'G-MQ9Z5FX00Q',
  );
}
